// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9JNKNB666hXttBrpmQ-0OjRCGqjJj0Z4',
    appId: '1:174568523442:web:0bbe3ddc24e3fc5d48ebab',
    messagingSenderId: '174568523442',
    projectId: 'fitflut-ac7f1',
    authDomain: 'fitflut-ac7f1.firebaseapp.com',
    storageBucket: 'fitflut-ac7f1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv_lgGNy2AJREqv_r2IcQ6kfoO-FTepyI',
    appId: '1:174568523442:android:53ddfda9afda478848ebab',
    messagingSenderId: '174568523442',
    projectId: 'fitflut-ac7f1',
    storageBucket: 'fitflut-ac7f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDMuP0Njhbzv2s0Dth38vc_vSsxsw6nnM',
    appId: '1:174568523442:ios:1234320680b7d74d48ebab',
    messagingSenderId: '174568523442',
    projectId: 'fitflut-ac7f1',
    storageBucket: 'fitflut-ac7f1.firebasestorage.app',
    iosClientId: '174568523442-061en4vt9lmdiafvroqudlj4uekqu68a.apps.googleusercontent.com',
    iosBundleId: 'com.brausjonas.fitflut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDMuP0Njhbzv2s0Dth38vc_vSsxsw6nnM',
    appId: '1:174568523442:ios:1234320680b7d74d48ebab',
    messagingSenderId: '174568523442',
    projectId: 'fitflut-ac7f1',
    storageBucket: 'fitflut-ac7f1.firebasestorage.app',
    iosClientId: '174568523442-061en4vt9lmdiafvroqudlj4uekqu68a.apps.googleusercontent.com',
    iosBundleId: 'com.brausjonas.fitflut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9JNKNB666hXttBrpmQ-0OjRCGqjJj0Z4',
    appId: '1:174568523442:web:2c40e1ae99e7141a48ebab',
    messagingSenderId: '174568523442',
    projectId: 'fitflut-ac7f1',
    authDomain: 'fitflut-ac7f1.firebaseapp.com',
    storageBucket: 'fitflut-ac7f1.firebasestorage.app',
  );

}